import dataclasses


@dataclasses.dataclass
class Product:
    def __init__(self, data: dict):
        self.product_id = data.get('productId')
        self.category_id = data.get('categoryId')
        self.product_code = data.get('productCode')
        self.product_name = data.get('productName')
        self.product_kana = data.get('productKana')
        self.tax_division = data.get('taxDivision')
        self.product_price_division = data.get('productPriceDivision')
        self.price = data.get('price')
        self.customer_price = data.get('customerPrice')
        self.cost = data.get('cost')
        self.attribute = data.get('attribute')
        self.description = data.get('description')
        self.catch_copy = data.get('catchCopy')
        self.size = data.get('size')
        self.color = data.get('color')
        self.tag = data.get('tag')
        self.group_code = data.get('groupCode')
        self.url = data.get('url')
        self.print_receipt_product_name = data.get('printReceiptProductName')
        self.display_sequence = data.get('displaySequence')
        self.sales_division = data.get('salesDivision')
        self.stock_control_division = data.get('stockControlDivision')
        self.display_flag = data.get('displayFlag')
        self.division = data.get('division')
        self.product_option_group_id = data.get('productOptionGroupId')
        self.point_not_applicable = data.get('pointNotApplicable')
        self.tax_free_division = data.get('taxFreeDivision')
        self.supplier_product_no = data.get('supplierProductNo')
        self.calc_discount = data.get('calcDiscount')
        self.staff_discount_rate = data.get('staffDiscountRate')
        self.use_category_reduce_tax = data.get('useCategoryReduceTax')
        self.reduce_tax_id = data.get('reduceTaxId')
        self.reduce_tax_price = data.get('reduceTaxPrice')
        self.reduce_tax_customer_price = data.get('reduceTaxCustomerPrice')
        self.app_start_date_time = data.get('appStartDateTime')
        self.ins_date_time = data.get('insDateTime')
        self.upd_date_time = data.get('updDateTime')
